version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - '3002:3000'
    env_file:
      - ./src/env/production.env
    depends_on:
      - db
  db:
    image: mysql:8.0.3
    platform: linux/x86_64
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: WFxKSZbug42Eaw4TFk
      MYSQL_DATABASE: logcon
      MYSQL_USER: logcon
      MYSQL_PASSWORD: 8V4WzkXXxtVhTYYyUJ
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
